## ndarry的索引(index),切割(slice)
https://numpy.org/

In [ ]:
import numpy as np

arr = np.arange(10)
arr[0]  
arr[-1]
arr[:3]
arr[-3:]

array([7, 8, 9])

python
import numpy as np

arr = np.arange(10) 產生一個包含 0 到 9 的一維陣列：
arr[0]  
arr[-1] array([0, 1, 2, 3, 4, 5, 取出陣列的第一個元素，結果為 0`
arr[:3] 取出陣列的前 3 個元素（索引 0, 1, 2），結果為 array([0,[2])
arr[-3:] 取出陣列的最後 3 個元素，結果為 array()

In [8]:
import random
random.randint(50,100)

65

In [9]:
np.random.randint(50, 101, size=5)
scores = np.random.randint(50, 101, size=(50,5))
scores.size
scores.shape                         

np.random.randint(50, 101, size=5)
scores = np.random.randint(50,101, size=(50, 5))
scores.size
scores.shape

(50, 5)

In [21]:
scores[:,0] 

array([83, 70, 61, 84, 73, 74, 53, 61, 64, 95, 79, 88, 59, 97, 76, 58, 53,
       83, 52, 64, 61, 95, 80, 67, 75, 82, 58, 93, 93, 70, 92, 62, 71, 64,
       68, 83, 53, 86, 90, 51, 78, 56, 77, 52, 60, 88, 52, 85, 97, 86])

scores[:,0]  -是 NumPy 陣列的切片語法，用於取得二維陣列
0 表示第 1 欄（索引 0）

In [11]:
scores[:,0]
scores[:,0:1]

array([[83],
       [70],
       [61],
       [84],
       [73],
       [74],
       [53],
       [61],
       [64],
       [95],
       [79],
       [88],
       [59],
       [97],
       [76],
       [58],
       [53],
       [83],
       [52],
       [64],
       [61],
       [95],
       [80],
       [67],
       [75],
       [82],
       [58],
       [93],
       [93],
       [70],
       [92],
       [62],
       [71],
       [64],
       [68],
       [83],
       [53],
       [86],
       [90],
       [51],
       [78],
       [56],
       [77],
       [52],
       [60],
       [88],
       [52],
       [85],
       [97],
       [86]])

scores[:,0] 回傳一維陣列（shape 為 (n,)），其中 n 是列數。
scores[:,0:1] 回傳二維陣列（shape 為 (n, 1)），保持原本的列數和欄數結構。
取出所有列的第 0 欄到第 1 欄（不含 1）的子陣列，也就是只取第 0 欄，但保持二維結構

In [13]:
scores[0,:]
scores[0:1,:]

array([[83, 71, 54, 73, 54]])

scores[0,:] 回傳一維陣列（shape 為 (m,)，m 為欄數）
scores[0:1,:] 取出第 0 列到第 1 列（不含 1），也就是只取第 0 列，但保持二維結構。
輸出形狀：回傳二維陣列（shape 為 (1, m)）

scores 是一個變數名稱，通常用來表示一個 NumPy 陣列（ndarray），
裡面可能存放著多筆數值資料，常見於存放學生分數、測試結果或其他數值資料的情況

In [14]:
scores

array([[ 83,  71,  54,  73,  54],
       [ 70,  68,  94,  95,  84],
       [ 61,  74,  82,  95,  63],
       [ 84,  65,  87,  88,  89],
       [ 73,  78,  65, 100,  52],
       [ 74,  58, 100,  53, 100],
       [ 53,  87,  84,  69,  64],
       [ 61,  93,  55,  57,  81],
       [ 64,  87,  55,  69,  61],
       [ 95,  70,  75,  52,  73],
       [ 79,  69,  84,  81,  54],
       [ 88,  84,  53,  84,  92],
       [ 59,  96,  55,  54,  99],
       [ 97,  53,  98, 100,  76],
       [ 76,  54,  99,  60,  98],
       [ 58,  69,  79,  60,  88],
       [ 53,  75,  88,  81,  92],
       [ 83,  66,  66,  87,  79],
       [ 52,  80,  61,  67,  79],
       [ 64,  52,  76,  62,  52],
       [ 61,  87,  66,  84,  66],
       [ 95,  75,  86,  53,  83],
       [ 80,  64,  60,  67,  78],
       [ 67, 100,  96,  61,  78],
       [ 75,  87,  79,  61,  74],
       [ 82,  68,  84,  57,  95],
       [ 58,  55,  93,  71,  96],
       [ 93,  53,  71,  55,  87],
       [ 93,  64,  54,  83,  57],
       [ 70,  

In [15]:
np.sum(scores)

np.int64(18787)

np.sum(scores) 是 NumPy 的加總函數，用來計算陣列 scores 所有元素的總和

In [19]:
np.sum(scores,axis=1)
np.mean(scores, axis=1)


array([67. , 82.2, 75. , 82.6, 73.6, 77. , 71.4, 69.4, 67.2, 73. , 73.4,
       80.2, 72.6, 84.8, 77.4, 70.8, 77.8, 76.2, 67.8, 61.2, 72.8, 78.4,
       69.8, 80.4, 75.2, 77.2, 74.6, 71.8, 70.2, 66. , 72. , 70.4, 84. ,
       71.6, 71.2, 74.6, 68.8, 93.6, 84. , 88.6, 77. , 82.4, 77.6, 68.6,
       68.6, 82.2, 70.2, 85. , 77. , 73. ])

np.sum(scores, axis=1) 功能：計算 scores 陣列每一列的總和。
說明：axis=1 代表沿著欄（column）方向運算，也就是對每一列的所有元素加總。
np.mean(scores, axis=1) 功能：計算 scores 陣列每一列的平均值。
說明：axis=1 代表沿著欄方向運算，也就是對每一列的所有元素取平均。

In [27]:
# 使用比較運算子
arr = np.random.randn(5)
arr > 0

array([ True,  True, False, False,  True])

np.random.randn(5) 會產生一個長度為 5 的一維陣列，元素是標準常態分布（平均值 0，標準差 1）的隨機數。
arr > 0 這會對陣列中的每個元素進行「是否大於 0」的判斷，回傳一個同樣長度的布林陣列（True/False）

In [28]:
np.where(arr >0,1,0)

array([1, 1, 0, 0, 1])

np.where(arr > 0, 1, 0) 會根據條件，將 arr 中大於 0 的元素標記為 1，其餘標記為 0。
回傳一個同樣形狀的陣列，元素值為 1 或 0。這是數據處理、特徵工程中非常常用的技巧

In [29]:
np.where(arr >0,1, arr)

array([ 1.        ,  1.        , -0.69970808, -0.14914837,  1.        ])

np.where(arr > 0, 1, arr) 會將正數元素變成 1，其他元素（0 或負數）保持原值。
結果是一個和 arr 形狀相同的新陣列，這種操作在數據標記、資料轉換時非常實用