https://www.perplexity.ai/search/1f6d8098-e981-44bf-b915-b14b9e9052da

### numpy的索引和切割

In [1]:
import numpy as np
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [12]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [9]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [8]:
np.random.rand(3, 4)

array([[0.26564108, 0.04953813, 0.8116245 , 0.06874766],
       [0.89178963, 0.33287287, 0.51111633, 0.39319567],
       [0.11289389, 0.20290429, 0.58405356, 0.18092331]])

In [7]:
scores = np.random.randint(50,101,size=(50, 5))


In [3]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
import numpy as np
scores = np.random.randint(50,101,size=(5, 5))
scores

array([[65, 70, 53, 83, 68],
       [66, 74, 83, 54, 58],
       [77, 62, 53, 62, 87],
       [91, 65, 83, 77, 66],
       [99, 54, 98, 52, 63]])

這段程式碼的功能是產生一個 5x5 的隨機整數陣列，並將結果存入變數 scores
- import numpy as np 將 NumPy 套件匯入，並簡寫為 np，方便後續使用 NumPy 的功能。
- np.random.randint(50, 101, size=(5, 5))
-np.random.randint() 是 NumPy 用來產生隨機整數的函數。
第一個參數 50：產生的隨機整數下限（包含 50）。
第二個參數 101：產生的隨機整數上限（不包含 101），也就是最大值為 100。
-size=(5, 5)：指定輸出的陣列形狀為 5 列 5 行（5x5），共 25 個隨機整數。
產生的每個數字都會落在 50 到 100 之間（包含 50 和 100）。

In [14]:
scores[:3,2:]

array([[53, 83, 68],
       [83, 54, 58],
       [53, 62, 87]])

scores：5x5 的二維陣列。

:3：在列（row）方向，選取第 0、1、2 列（共前三列，不含第 3 列）。

2:：在欄（column）方向，選取第 2、3、4 欄（從第 2 欄起到最後一欄）。

換句話說，scores[:3, 2:] 會取得原陣列左上角 3 列、右側 3 欄所構成的 3x3 子陣列。

In [15]:
scores[4]
scores[4,:]
scores[4:,:]

array([[99, 54, 98, 52, 63]])

In [16]:
scores[:,:2]

array([[65, 70],
       [66, 74],
       [77, 62],
       [91, 65],
       [99, 54]])

### numpy的統計工具

In [25]:
scores = np.random.randint(50,101,size=(5,5))
scores

array([[ 68,  85,  66,  79, 100],
       [ 75,  87,  84,  55,  50],
       [ 88,  88,  78,  88,  92],
       [ 95,  77,  66,  97,  61],
       [ 73,  77,  67,  65,  90]])

In [24]:
scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]

array([339, 335, 341, 382, 366])

In [ ]:
# 加總
np.sum(scores,axis=1)

array([339, 335, 341, 382, 366])

In [ ]:
# 平均
np.mean(scores,axis=1)

array([67.8, 67. , 68.2, 76.4, 73.2])

In [19]:
# 最大值
np.max(scores,axis=1)

array([83, 83, 87, 91, 99])

In [22]:
# 最小值
np.min(scores,axis=1)

array([53, 54, 53, 65, 52])

In [20]:
# 中間數
np.median(scores,axis=1)

array([68., 66., 62., 77., 63.])

In [23]:
# 標準差
np.std(scores,axis=1)

array([ 9.62081078, 10.54514106, 12.15565712,  9.95188424, 20.9895212 ])